---
- name: Add nginx ppa
  apt_repository: repo=ppa:hda-me/nginx-stable

- name: Install nginx
  apt: pkg={{ packages }} state=present
  vars:
    packages:
      - brotli
      - nginx
      - nginx-module-brotli

- name: Generate Diffie-Hellman keys
  openssl_dhparam: path=/etc/nginx/dhparam.pem size=4096

- name: Remove default nginx site
  file: path="/etc/nginx/sites-enabled/default" state=absent

- name: Update default nginx.conf
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: Ensure "/etc/nginx/shared-config" directory exists
  file: path=/etc/nginx/shared-config state=directory

- name: Copy shared/common configs
  copy: src={{ item }} dest=/etc/nginx/shared-config/{{ item }}
  with_items:
    - general.conf
    - proxy.conf
    - security.conf

- name: Install nginx virtual host configs in sites-available
  template:
    src: "virtual_host.conf.j2"
    dest: /etc/nginx/sites-available/{{ item.type }}.{{ item.domain }}.conf
  with_items: "{{ nginx.proxy_configs }}"
  notify: reload nginx
