---
- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install security packages
  apt: state=present pkg='{{ security_packages }}'

- name: Enable unattended upgrades
  copy: src=apt_unattended_upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades

# Configure ufw to only allow the specified ports through
# every other connection will be denied (policy=deny)
- name: Configure required ufw TCP ports for app
  ufw: rule=allow port={{ item }} proto=tcp
  with_items: "{{ ufw_open_ports }}"

- name: Enable ufw
  ufw: state=enabled policy=deny

# Lock down SSH to only allow key-based connections and disallow
# ssh login as root user (e.g. disallow 'ssh root@server.com')
- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: restart ssh

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: restart ssh
