# Reboot ####################################################################
# There is a chance we might have to reboot after installing all these new
# packages. If that is the case the /var/run/reboot-required flag is set. In
# that case reboot the machine and wait for it to come back up. Do nothing if
# no reboot is required.
- name: Check if reboot is required
  stat: path=/var/run/reboot-required
  register: reboot_file

- name: Reboot if needed
  shell: sleep 2 && shutdown -r now "Ansible initiated"
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_file.stat.exists

- name: Wait for reboot to finish
  local_action: wait_for host={{ inventory_hostname }} state=started delay=15 timeout=120
  become: no
  when: reboot_file.stat.exists
