---
- name: Add certbot ppa
  apt_repository: repo=ppa:certbot/certbot

- name: Install certbot
  apt: pkg="{{ packages }}" state=present
  vars:
    packages:
      - software-properties-common
      - certbot
      - python-certbot-nginx
      - python3-venv
      - python3-pip

- name: Install Gandi DNS certbot plugin
  pip: name=certbot-plugin-gandi state=latest

- name: Ensure "/etc/letsencrypt/gandi" directory exists
  file: path=/etc/letsencrypt/gandi state=directory

- name: Configure Gandi DNS certbot plugin
  copy: content="certbot_plugin_gandi:dns_api_key={{ certs.gandi_api_key }}"
        dest=/etc/letsencrypt/gandi/gandi.ini
        mode=0600

- name: Generate wildcard certs for domain {{ certs.domain }}
  shell: >-
    certbot certonly
    -a certbot-plugin-gandi:dns
    --certbot-plugin-gandi:dns-credentials /etc/letsencrypt/gandi/gandi.ini
    -d {{ certs.domain }} -d *.{{ certs.domain }}
    --server {{ certs.acme_server }}
    --email {{ certs.email }}
    --agree-tos
    --noninteractive
    --staple-ocsp
  register: result

- name: Result of wildcard certs generation
  debug: msg="{{ result.stdout_lines }}"

- name: Dry run cert auto-renew
  shell: certbot renew --dry-run
  register: result

- name: Result of renews dry-run
  debug: msg="{{ result.stdout_lines }}"
