---
- name: Create deploy user
  user: name={{ elixir_app.deploy_user_name }} shell={{ elixir_app.deploy_user_shell }}

- name: Add pubkey to deploy_user
  authorized_key: user={{ elixir_app.deploy_user_name }}
                  key="{{ lookup('file', '{{ elixir_app.deploy_user_pubkey }}' ) }}"
                  exclusive=yes
                  manage_dir=yes

- name: Add deploy script
  template: src=deploy.sh.j2
            dest="/usr/local/bin/{{ elixir_app.name }}_deploy.sh"
            owner=root
            group=root
            mode=0755

- name: Allow deploy user to sudo commands for deployment only
  template:
    src: "deploy.sudoers.j2"
    dest: /etc/sudoers.d/{{ elixir_app.deploy_user_name }}
    validate: 'visudo -cf %s'
