---
# Add a app user which will run an elixir app
- name: Create the app user
  user: name={{ elixir_app.name }} shell={{ elixir_app.shell }}

- name: Ensure /etc/{{ elixir_app.name }} dir exists
  file: path=/etc/{{ elixir_app.name }} state=directory

- name: Set {{ elixir_app.name|upper }} ENV's
  template: src={{ elixir_app.env_template_path }}
            dest=/etc/{{ elixir_app.name }}/{{ elixir_app.name }}_{{ item.type }}_env
            owner={{ elixir_app.name }}
            group={{ elixir_app.name }}
  with_items: "{{ elixir_app.blue_green_config }}"

- name: Install a script to quickly run commands against the active (green or blue) app
  template: src=app_run.sh.j2
            dest=/usr/local/bin/run_{{ elixir_app.name }}
            owner={{ elixir_app.name }}
            group={{ elixir_app.name }}
            mode=0755

- name: Add EPMD service
  copy: src=epmd.service dest=/etc/systemd/system/epmd.service
  register: systemd_service

- name: Ensure systemd script is installed (blue + green)
  template: src=app.systemd.service.j2
            dest=/etc/systemd/system/{{ elixir_app.name }}_{{ item.type }}.service
  with_items: "{{ elixir_app.blue_green_config }}"
  register: systemd_service

- name: Reload systemctl daemon
  command: systemctl daemon-reload
  when: systemd_service.changed

- name: Enable & Start EPMD service
  systemd: name=epmd.service enabled=yes state=started

- name: Ensure both blue and green app systemd scripts are disabled; will be enabled by deployer.
  systemd: name={{ elixir_app.name }}_{{ item.type }}.service
           enabled=no
  with_items: "{{ elixir_app.blue_green_config }}"
